#!/usr/bin/env python3
"""Offline, deterministic quality gate for Markdown/Discord digests.

Exit codes: 0 pass, 1 content violations, 2 CLI/input errors. No network or
semantic fact checking. All top-level bullets are content unless they are an
explicit attribution line. Only clearly proposed next-week experiments may
omit citations. URL identity normalizes host/scheme case and removes fragments and
common tracking parameters; redirects and event identity are not checked.
"""
import argparse
from html import unescape
from pathlib import Path
import re
import sys
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

BULLET = re.compile(r"^( *)([-•])\s+(.+)$")
MARKDOWN_START = re.compile(r"\[([^\]\n]*)\]\(")
ANGLE = re.compile(r"<([^<>\s]+)>")
RAW_URL = re.compile(r"https?://[^\s<>\[\]，。；！？]+", re.I)
REPO = re.compile(r"(?<![\w/])([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)(?![\w/])")
VERSION = re.compile(r"(?<!\w)v?\d+\.\d+(?:\.[\w.+-]+)*(?:-[\w.-]+)?", re.I)
CJK = re.compile(r"[\u3400-\u9fff\U00020000-\U0002ffff]")
GROWTH = re.compile(r"\+\s*\d[\d,]*(?:\.\d+)?\s*[kmb万亿]?\s*/\s*(?:day\b|日)", re.I)
SCORE = re.compile(r"^(?:🔥\s*\d|\[?\s*(?:quality[ _-]?score|quality score|score|质量分|质量评分)\s*[:：=]\s*\d)", re.I)
LEGACY = re.compile(r"(?<![A-Za-z])KOL(?![A-Za-z])|关键人物动态|GitHub\s*(?:Trending|趋势|热门)|^Trending\b", re.I)
RELEASE_HEADING = re.compile(r"\breleases?\b|发布精选|版本发布|开源发布|GitHub\s*发布", re.I)
COMBINED_HEADING = re.compile(r"\btools?\b|工具", re.I)
EXPERIMENT_HEADING = re.compile(r"下周.*(?:实验|尝试|验证)|next[ -]week.*(?:experiment|try|validation)", re.I)
PROPOSAL = re.compile(r"^(?:建议|尝试|计划|拟|试用|验证|对比|测试|评估|复现|可以|不妨|try\b|test\b|evaluate\b|compare\b|experiment\b|consider\b|plan\b)", re.I)


def plain(text):
    return re.sub(r"[*_`]", "", text).strip()


def attribution(line):
    return bool(re.match(r"^(?:🤖\s*)?(?:Generated by\b|Powered by\b|由\s*tech-news-digest.*生成)", plain(line), re.I))


def heading(line):
    stripped = line.strip()
    match = re.match(r"^#{1,6}\s+(.+?)(?:\s+#+)?$", stripped)
    if match:
        return plain(match.group(1))
    if re.fullmatch(r"\*\*.+\*\*", stripped):
        return plain(stripped)
    return None


def valid_url(url):
    """Validate HTTP(S) syntax, not network reachability."""
    if re.search(r"[\s<>\x00-\x1f]", url):
        return False
    try:
        parsed = urlsplit(url)
        # Accessing port also validates nonnumeric/out-of-range ports.
        _ = parsed.port
        host = (parsed.hostname or "").encode("idna").decode("ascii")
        if ":" not in host and not all(
            re.fullmatch(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?", label)
            for label in host.rstrip(".").split(".")
        ):
            return False
        return (parsed.scheme.lower() in ("http", "https") and bool(parsed.hostname)
                and not parsed.username and not parsed.password
                and not re.search(r"[\\{}|^`]", parsed.netloc))
    except (ValueError, UnicodeError):
        return False


def links(text):
    """Return (URL, start, end) for inline Markdown and angle autolinks.

    Balanced parentheses in destinations and optional quoted titles work;
    reference-style links and HTML anchors are deliberately outside this gate.
    """
    result = []
    for match in MARKDOWN_START.finditer(text):
        pos = match.end()
        depth = 1
        quote = None
        while pos < len(text) and depth:
            char = text[pos]
            if char == "\\":
                pos += 2
                continue
            if quote:
                if char == quote:
                    quote = None
            elif char in ('"', "'") and pos > match.end() and text[pos - 1].isspace():
                quote = char
            elif char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            pos += 1
        if depth:
            continue
        target = text[match.end():pos - 1].strip()
        # Only split off a well-formed optional title, never whitespace in a URL.
        target = re.sub(r'\s+(?:"[^"\n]*"|\'[^\'\n]*\')$', '', target)
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        result.append((unescape(target), match.start(), pos))
    for match in ANGLE.finditer(text):
        if not any(start <= match.start() < end for _, start, end in result):
            result.append((unescape(match.group(1)), match.start(), match.end()))
    return sorted(result, key=lambda value: value[1])


def source_urls(text):
    """Include bare URLs in deduplication, but not as qualifying citations."""
    found = links(text)
    result = [url for url, _, _ in found if valid_url(url)]
    for match in RAW_URL.finditer(text):
        if any(start <= match.start() < end for _, start, end in found):
            continue
        url = match.group().rstrip(".,;:!?)")
        if valid_url(url):
            result.append(url)
    return result


def url_key(url):
    parts = urlsplit(url)
    query = [(key, value) for key, value in parse_qsl(parts.query, keep_blank_values=True)
             if not key.lower().startswith("utm_") and key.lower() not in ("fbclid", "gclid")]
    return urlunsplit((parts.scheme.lower(), parts.netloc.lower(), parts.path, urlencode(query), ""))


def section_gate(title, mode):
    """Exact editorial headings only; don't infer a section from prose."""
    title = re.sub(r"^[^\w\u3400-\u9fff]+", "", title).strip().lower()
    title = re.sub(r"\s*[（(].*$", "", title).strip()
    if title in ("值得读", "延伸阅读", "阅读", "reading", "博客精选", "blog picks"):
        return "reading", 3 if mode == "daily" else 4
    if title in ("项目发现", "github 项目发现", "值得试", "project discovery", "worth trying"):
        return "discovery", 3
    if mode == "daily" and title in ("kol 动态", "kol动态", "kol updates", "关键人物动态"):
        return "kol", 3
    if mode == "daily" and title in ("可行动", "action", "actions"):
        return "action", 2
    if mode == "weekly" and title in ("观点与深度阅读", "观点 / 深度阅读", "viewpoints / deep reading", "viewpoints and deep reading", "deep reading", "viewpoints"):
        return "reading", 4
    if mode == "weekly" and (title in ("下周关注", "下周观察", "next-week watch", "next week watch", "下周验证清单") or EXPERIMENT_HEADING.search(title)):
        return "watch", 3
    return None


def repository(text, urls):
    for url in urls:
        parts = urlsplit(url)
        path = parts.path.strip("/").split("/")
        if parts.hostname and parts.hostname.lower() in ("github.com", "www.github.com") and len(path) >= 2:
            return "/".join(path[:2]).removesuffix(".git").lower()
    # Only inspect the label before explanatory prose, not arbitrary slashes.
    label = re.split(r"\s[—–]|\s-\s|：", text, maxsplit=1)[0]
    match = REPO.search(plain(label))
    return match.group(1).lower() if match else None


def explanation(text, repo):
    # Keep non-source Markdown labels (often the actual repository title).
    value = text
    for url, start, end in reversed(links(text)):
        label = re.match(r"\[([^\]]*)\]", text[start:end])
        replacement = label.group(1) if label else ""
        # Citation labels carry no explanation; substantive linked text does.
        if re.fullmatch(r"(?:来源|源|发布|原文|链接|详情|source|release(?: notes)?|link|read more)", plain(replacement), re.I):
            replacement = ""
        value = value[:start] + replacement + value[end:]
    value = RAW_URL.sub("", value)
    if repo:
        value = re.sub(re.escape(repo), "", value, flags=re.I)
    value = VERSION.sub("", value)
    value = plain(value)
    # Formatting delimiters around the repo/version are not explanation text.
    return value.strip(" \t\r\n—–-:：|()（）")


def body_length(text):
    """Exclude only URL targets; retain labels, markup, titles and whitespace."""
    found = links(text)
    size = len(text)
    for _, start, end in found:
        fragment = text[start:end]
        prefix = MARKDOWN_START.match(fragment)
        target = fragment[prefix.end():-1].strip() if prefix else fragment[1:-1]
        target = re.sub(r'\s+(?:"[^"\n]*"|\'[^\'\n]*\')$', '', target)
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        size -= len(target)
    for match in RAW_URL.finditer(text):
        if not any(start <= match.start() < end for _, start, end in found):
            size -= len(match.group().rstrip(".,;:!?)"))
    return size


def check_topic_headings(lines, expected):
    """Use caller-supplied localized labels, never hard-code configured topics."""
    errors = []
    sections = [(i, heading(line)) for i, line in enumerate(lines) if heading(line) is not None]
    positions = []
    for title in expected:
        matches = [(i, pos) for i, (pos, found) in enumerate(sections) if found == plain(title)]
        if len(matches) != 1:
            errors.append(f"[topic-heading] expected exactly one configured heading: {title}")
            continue
        index, pos = matches[0]
        positions.append(pos)
        end = sections[index + 1][0] if index + 1 < len(sections) else len(lines)
        content = [line.strip() for line in lines[pos + 1:end] if line.strip() and line.strip() != "---"]
        if not content:
            errors.append(f"[coverage-note] empty topic needs an honest coverage note: {title}")
    if positions != sorted(positions):
        errors.append("[topic-order] configured topics must retain their order")
    return errors


def validate(text, mode="daily", topic_headings=None):
    """Return human-readable violations, each with a stable bracketed code."""
    if mode not in ("daily", "weekly"):
        raise ValueError("mode must be daily or weekly")
    errors = []
    lines = text.splitlines()
    if mode == "weekly":
        size = body_length(text)
        if size > 10000:
            errors.append(f"[body-limit] {size} body characters exceeds weekly cap 10000")
        if topic_headings:
            errors.extend(check_topic_headings(lines, topic_headings))
    matches = [BULLET.match(line) for line in lines]
    # A uniformly indented Markdown list is valid; deeper bullets are children.
    indents = [len(match.group(1)) for match in matches if match and len(match.group(1)) <= 3]
    base = min(indents, default=0)
    blocks = []
    current = None
    section = ""
    content_lines = []
    for number, line in enumerate(lines, 1):
        stripped = line.strip()
        bullet = BULLET.match(line)
        candidate = bullet.group(3) if bullet else stripped
        if attribution(candidate):
            current = None
            continue
        content_lines.append((number, line))
        if GROWTH.search(line):
            errors.append(f"line {number}: [daily-growth] unsupported +N/day or +N/日 metric")
        if re.search(r"(?:Data\s+Sources|数据源(?:统计)?|数据来源(?:统计)?)\s*[:：]", plain(line), re.I):
            errors.append(f"line {number}: [operational-footer] remove data-source statistics")
        title = heading(line)
        if title is not None:
            section = title
            current = None
            if LEGACY.search(title) and not (mode == "daily" and re.search(r"KOL|关键人物动态", title, re.I)):
                errors.append(f"line {number}: [legacy-heading] remove fixed KOL/Trending section")
            continue
        if re.fullmatch(r"\s*(?:-{3,}|\*{3,}|_{3,})\s*", line):
            current = None
            continue
        if bullet and len(bullet.group(1)) == base:
            current = {"line": number, "section": section, "text": bullet.group(3)}
            blocks.append(current)
        elif current is not None and stripped:
            current["text"] += "\n" + stripped

    limit, release_limit = (30, 3) if mode == "daily" else (35, 5)
    if not blocks:
        errors.append("[empty-digest] no top-level content bullets")
    if len(blocks) > limit:
        errors.append(f"[item-limit] {len(blocks)} content bullets exceeds {mode} cap {limit}")

    seen_urls = {}
    for number, line in content_lines:
        for url in source_urls(line):
            key = url_key(url)
            if key in seen_urls:
                errors.append(f"line {number}: [duplicate-url] {url} (first on line {seen_urls[key]})")
            else:
                seen_urls[key] = number

    release_count = 0
    seen_repos = {}
    section_counts = {}
    for block in blocks:
        number, body, title = block["line"], block["text"], block["section"]
        gate = section_gate(title, mode)
        if gate:
            name, cap = gate
            section_counts[name] = section_counts.get(name, 0) + 1
            if section_counts[name] == cap + 1:
                errors.append(f"line {number}: [section-limit] {name} exceeds {mode} cap {cap}")
        citations = links(body)
        invalid = any(not valid_url(url) for url, _, _ in citations)
        proposed = EXPERIMENT_HEADING.search(title) and (
            PROPOSAL.search(plain(body)) or re.search(r"拟议|尚未执行|proposed|not performed", title, re.I))
        if mode == "weekly" and gate and gate[0] == "watch":
            proposed = proposed or (PROPOSAL.search(plain(body)) and re.search(
                r"拟议实验|建议实验|proposed experiment|尚未执行|not performed", body, re.I))
        if invalid or (not any(valid_url(url) for url, _, _ in citations) and not proposed):
            errors.append(f"line {number}: [source-link] expected a valid HTTP(S) Markdown or angle source link")
        if SCORE.search(plain(body)):
            errors.append(f"line {number}: [quality-score] remove public quality-score prefix")
        urls = source_urls(body)
        repo = repository(body, urls)
        dedicated = RELEASE_HEADING.search(title) and not COMBINED_HEADING.search(title)
        if mode == "weekly" and re.search(r"关键发布", title):
            dedicated = True
        explicit = any(re.search(r"/releases(?:/|$)", urlsplit(url).path) for url in urls)
        labeled_release = bool(repo and VERSION.search(body) and RELEASE_HEADING.search(title))
        if not (dedicated or explicit or labeled_release):
            continue
        release_count += 1
        if repo:
            if repo in seen_repos:
                errors.append(f"line {number}: [duplicate-repo] {repo} (first on line {seen_repos[repo]})")
            seen_repos[repo] = number
        summary = explanation(body, repo)
        if CJK.search(summary) and len(summary) > 80:
            errors.append(f"line {number}: [release-length] explanation has {len(summary)} characters; cap is 80")
    if release_count > release_limit:
        errors.append(f"[release-limit] {release_count} releases exceeds {mode} cap {release_limit}")
    return errors


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="UTF-8 Markdown/Discord digest")
    parser.add_argument("--mode", required=True, choices=("daily", "weekly"))
    parser.add_argument("--topic-heading", action="append", default=[],
                        help="Weekly: repeat configured localized headings in order for heading/coverage checks")
    args = parser.parse_args(argv)
    try:
        text = args.input.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        print(f"ERROR: cannot read {args.input}: {exc}", file=sys.stderr)
        return 2
    errors = validate(text, args.mode, topic_headings=args.topic_heading)
    if errors:
        print(f"FAIL: {len(errors)} quality-gate violation(s)", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"PASS: {args.mode} digest satisfies deterministic quality gates")
    return 0


if __name__ == "__main__":
    sys.exit(main())
